name: junes_package
description: "widget and function for me"
version: 0.9.5
homepage: https://github.com/junes-flutter-packages/junes_package

environment:
  sdk: '>=3.2.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # backend
#  sqlite3_flutter_libs: ^0.5.3
#  path_provider: ^2.0.9
#  path: ^1.8.0 #flutter drive 1.8.1 over error
  get: ^4.6.5
  #  get_it: ^7.2.0
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  logger: ^2.0.2+1
  package_info_plus: ^5.0.1
#  cached_network_image: ^3.2.1
  connectivity_plus: ^5.0.2
  battery_plus: ^5.0.2
  device_info_plus: ^9.0.3
  network_info_plus: ^4.0.2
  sensors_plus: ^4.0.2
  share_plus: ^7.1.0
  #  app_review: ^2.1.1+1
  #  flutter_sms: ^2.3.3
#  encrypt: ^5.0.1
  easy_localization: ^3.0.3
  #    easy_localization: #^3.0.0
  #      git: https://github.com/melodysdreamj/easy_localization.git
#  easy_localization_loader: ^2.0.0
  intl: ^0.18.1
  flutter_native_splash: ^2.0.5
#  tmdb_api: ^2.0.0
  tuple: ^2.0.0
  random_string: ^2.3.1
#  animations: ^2.0.3
#  syncfusion_flutter_calendar: ^24.1.41
#  syncfusion_localizations: ^24.1.41
  english_words:
#  device_preview: ^1.1.0
#  http: ^1.1.0
  dio: ^5.3.3
#  json_annotation: ^4.4.0
  shared_preferences: ^2.2.2
  platform: ^3.0.2
#  flutter_form_builder: ^9.1.1
#  day_night_time_picker: ^1.0.3+1
#  table_calendar: ^3.0.4
#  flutter_calendar_carousel: ^2.1.0
  sqflite: ^2.0.1
#  encrypted_shared_preferences: ^3.0.0
#  flutter_phoenix: ^1.0.0
  csv: ^5.0.1
  faker_dart: ^0.2.1
#  uuid: ^3.0.6
#  quiver: ^3.0.1+1
#  flutter_oss_licenses: ^2.0.0+1
#  flutter_mailer: ^2.0.1
  event_bus: ^2.0.0
#  flutter_gen: ^5.1.0+1
#  dart_ipify: ^1.1.1

  # backend.work
  #  flutter_inappwebview: ^5.3.2 # no more managed
#  permission_handler: ^11.0.1
  google_mobile_ads: ^4.0.0
  firebase_core: ^2.19.0
  firebase_analytics: ^10.6.1
  firebase_performance: ^0.9.3+1
  firebase_crashlytics: ^3.4.1
  firebase_dynamic_links: ^5.4.1
  firebase_database: ^10.3.1
  firebase_storage: ^11.3.1
  firebase_auth: ^4.11.1
  google_sign_in: ^6.2.1
  #  flutter_facebook_auth: ^6.0.2
  sign_in_with_apple: ^5.0.0
  flutter_web_auth: ^0.5.0
  kakao_flutter_sdk: ^1.1.1
  flutter_naver_login: ^1.2.3
  firebase_remote_config: ^4.3.1
  firebase_messaging: ^14.7.1
  cloud_firestore: ^4.11.0
  awesome_notifications: ^0.8.2
  cloud_functions: ^4.0.3
  contacts_service: ^0.6.3
  #  gsheets: ^0.4.2
  #
  #
  #  # frontend
#  google_fonts: ^6.1.0
#  getwidget: ^4.0.0
#  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.5.3+2
#  flutter_neumorphic: ^3.2.0
  after_layout: ^1.2.0
#  infinite_listview: ^1.1.0
#  sticky_headers: ^0.3.0+2
  auto_size_text: ^3.0.0
#  flutter_spinkit: ^5.2.0
  flutter_gradient_colors: ^2.1.1
#  badges: ^3.0.2
  get_time_ago: ^1.1.3
#  bubble: ^1.2.1
#  toggle_switch: ^2.0.1
#  list_tile_switch: ^1.0.0
#  animated_toggle_switch: ^0.8.0
#  flutter_advanced_switch: ^3.0.1
#  direct_select: ^2.0.0
#  widget_mask: ^1.0.0
#  flutter_zoom_drawer: ^3.0.2
#  animate_do: ^3.0.2
#  flutter_bounce: ^1.1.0
#  bouncing_widget: ^2.0.0
#  flutter_vibrate: ^1.3.0
  adaptive_dialog: ^2.0.0
  percent_indicator: ^4.2.2
  flex_color_scheme: ^7.3.1
#  custom_navigation_bar: ^0.8.2
#  google_nav_bar: ^5.0.5
  keyboard_attachable: ^2.1.0
  flutter_color: ^2.0.0
  modal_bottom_sheet: ^3.0.0-pre
  random_color: ^1.0.6-nullsafety
  styled_widget: ^0.4.0+3
  flutter_speed_dial: ^7.0.0

  # icons
#  flutter_font_icons:
  material_design_icons_flutter:
#  fluttericon:
#  line_awesome_flutter: ^2.0.0
#  eva_icons_flutter: ^3.1.0
#  icofont_flutter:
#  font_awesome_flutter:
#  flutter_boxicons:



  #2022/1
  #  translator: ^0.1.7
#  sembast: ^3.1.1+1
  url_launcher: ^6.0.20
  clipboard: ^0.1.3
#  geolocator: ^10.1.0
#  distance: ^1.0.0
  #  google_maps_flutter: ^2.1.1
#  flutter_map: ^6.0.0
#  latlong2: ^0.9.0
#  email_validator: ^2.0.1
  #  app_tracking_transparency: ^2.0.2+1
#  location: ^5.0.3
  page_transition: ^2.0.9
#  basic_utils: ^5.4.2
  #  wakelock: ^0.6.2
#  stop_watch_timer: ^3.0.2
  auto_orientation: ^2.2.1
#  need_resume: # ^1.0.6
#    git: https://github.com/melodysdreamj/need_resume.git
#  lottie: ^2.3.0
#  extension_google_sign_in_as_googleapis_auth: ^2.0.4
#  sembast_web: ^2.0.1+1
#  rename: ^3.0.0
#  advertising_id: ^2.3.0
#  flutter_svg: ^2.0.4
#  geocoding: ^2.0.5
#  flutter_sticky_header: ^0.6.0

  #2022/2
  #  background_fetch: ^1.0.3 # no more use because of many problems
#  flutter_fgbg: ^0.3.0
#  flutter_easyloading: ^3.0.5
#  workmanager: ^0.5.0
  #    git:
  #      url: https://github.com/fluttercommunity/flutter_workmanager.git
  #      ref: 9f3eddb7706030b8a84cc0981130a20b77cc167d
  timeago: ^3.2.2
#  google_static_maps_controller: ^1.0.0
#  flash: ^3.0.5+1
#  back_button_interceptor: ^7.0.0
#  settings_ui: ^2.0.2
#  telephony: ^0.2.0
#  in_app_review: ^2.0.4
  firebase_app_check: ^0.2.1+5
  country_codes: ^2.1.1
#  country_code_picker: ^3.0.0
  phone_number: ^2.0.1
  libphonenumber: ^2.0.2

  #2022/3
#  fluttertoast: ^8.2.4
  #  cat_avatar_generator: ^0.1.0
#  webview_flutter: ^4.0.0
#  cryptography: ^2.0.5
#  crypto: ^3.0.1

  # 2022/4
  shimmer: ^3.0.0
  tutorial_coach_mark: ^1.2.3
#  flutter_intro: ^3.0.2
  material_dialogs: ^1.1.1
  shimmer_animation: ^2.1.0+1
  flutter_markdown: ^0.6.9+1
#  flutter_inappwebview: ^6.0.0-beta.22
#  internet_connection_checker: ^1.0.0+1

  # 2022/5
  #  google_mlkit_face_detection: ^0.3.0
#  camera: ^0.10.3+2
  image_picker: ^1.0.7
#  in_app_purchase: ^3.0.2
#  video_player: ^2.4.0
  #  disk_space: ^0.2.1
  #  dart_tags: ^0.4.0
#  image: ^3.1.3
#  flutter_staggered_grid_view: ^0.7.0
#  screenshot: ^2.1.0
#  double_linked_list: ^2.0.1
  deep_collection: ^1.0.2
#  sign_button: ^2.0.2
#  image_stack: ^2.1.1
#  images_picker: ^1.2.11

  # 2022/7
#  flutter_colorpicker: ^1.0.3
#  unsplash_client: ^2.1.0+3
#  carousel_slider: ^4.1.1
#  open_mail_app: ^0.4.5
#  flutter_slidable: ^3.0.0
#  indexed_list_view: ^3.0.1
#  bidirectional_listview: ^1.0.3
#  scrollable_positioned_list: ^0.3.2
#  loading_more_list: ^6.0.0
#  ff_annotation_route_library: ^3.0.0
#  extended_image: ^8.0.2
#  like_button: ^2.0.4
#  extended_sliver: ^2.1.3
#  extended_nested_scroll_view: ^6.0.0
#  pull_to_refresh_notification: ^3.0.0
#  flutter_list_view: ^1.1.18
#  pull_to_refresh: #^2.0.0
#  flutter_html: ^3.0.0-alpha.6
  #  flutter_html_all: ^3.0.0-alpha.6

  # 2022/8
#  isolated_worker: ^0.1.1
#  flutter_image_compress: ^2.0.4
#  hashtager: ^1.0.4
#  smooth_page_indicator: ^1.0.0+2
#  crop_your_image: ^0.7.2
  #  drishya_picker: ^2.0.0-dev-1
  #  photo_manager: ^2.8.1
#  oktoast: ^3.2.0
#  image_size_getter: ^2.1.2

  # 2022/9
  liquid_pull_to_refresh: ^3.0.1
#  sliding_sheet: ^0.5.2
#  map_launcher: ^3.1.0
  #  fluent_ui: ^3.12.0
  #  macos_ui: ^1.7.5
#  sidebarx: ^0.16.2
  file_picker: ^6.1.1
#  rflutter_alert: ^2.0.4
#  textfield_tags: ^2.0.2
#  filter_list: ^1.0.2
  #  chips_choice_null_safety: ^2.0.6
#  reorderables: ^0.6.0
#  loader_overlay: ^4.0.0
  #  flutter_r2:
  #    git: https://github.com/melodysdreamj/flutter_r2.git
#  confetti: ^0.7.0
#  sliding_up_panel: ^2.0.0+1
  #  amazon_cognito_identity_dart_2: ^3.0.0
  #  drive_helper: ^1.3.1
#  flutter_linkify: ^6.0.0
#  platform_maps_flutter: ^1.0.2

  # 2022/10
#  scroll_snap_list: ^0.9.1
#  gradient_borders: ^1.0.0
#  vibration: ^1.7.6
#  material_color_gen: ^2.0.0
  #  firebase_image: ^1.1.1
#  flutter_riverpod: ^2.0.2
#  hooks_riverpod: ^2.0.2
#  adaptive_theme: ^3.1.1
#  go_router: ^13.0.0

  # 2022/12
#  pointer_interceptor: ^0.10.0 # use in flutter_inappwebview
  #  appwrite: ^11.0.0

  # 2023/10
  flutter_secure_storage: ^9.0.0
  get_storage: ^2.1.1
#  auto_app_translate:

  # 2023/11
  gap: ^3.0.1
#  flutter_styled_toast: ^2.2.1

  # 2023/11
  flutter_contacts: ^1.1.7+1

  # 2024/1
  insta_assets_picker: ^2.2.1
  photo_manager: ^3.0.0-dev.5
  loading_indicator: ^3.1.1
  wechat_assets_picker:

  # 2024/1
  intl_phone_field: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
